version: "1.0"
services:
  httprunner:
    build:

    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306: 3306
  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
    - 5672: 5672
    - 5671: 5671
    - 25672: 25672
